# The `common' part is automatically included (and possibly overriden by all
# other flavors)
common:
    # Set a random string here
    secret_key: 9660c62e-9aff-44ec-ba87-1273ab9d2dc5


# This is the default configuration when no flavor is specified
dev:
    storage: local
    storage_path: /tmp/registry
    loglevel: debug


# This flavor stores the images in Glance (to integrate with openstack)
# See also: https://github.com/dotcloud/openstack-docker
openstack:
    storage: glance
    storage_alternate: local
    storage_path: /tmp/registry
    loglevel: debug